### ISSUE TITLE
Manual entry of coordinates

### ISSUE THREAD

**Issue by kjellmf** [orbat-mapper/orbat-mapper#222]
### Discussed in https://github.com/orbat-mapper/orbat-mapper/discussions/221

I was wondering if it might be feasible to incorporate an additional feature allowing us to manually input latitude and longitude coordinates for the location of a unit, in addition to the current option of selecting it from the map. Occasionally, we have coordinates with a higher level of precision, and selecting the exact coordinates on the map can be a bit challenging. </div>

**Comment by Vbsasuke26** [comment]
Thank you so much kjell :)
